---
baseURL: https://recipes.pharbison.dev/
languageCode: en-us
title: Family Recipes
theme:
  - github.com/nodejh/hugo-theme-mini
# googleAnalytics: G-LDY55SZ579
# params:
#   enableGoogleAnalytics: true
