---
name: github pages

on:   # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
# push:
  #   branches:
  #     - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint

  build-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build static web files
        run: hugo --minify
